  - name: Add R CRAN apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: E298A3A825C0D65DFD57CBB651716619E084DAB9

  - name: Add R cran apt repository
    apt_repository:
      repo: 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
      state: present
      filename: rcran
      update_cache: yes

  - name: Install R cran and dependencies
    apt:
      name:
        - r-base
        - r-base-core
        - r-recommended
      update_cache: yes

  - name: Change R libs file permissions
    file:
      path: '{{ item }}'
      mode: '0777'
      recurse: yes
    with_items:
      - /usr/share/R
      - /usr/lib/R
      - /usr/local/lib/R

  - name: Download Rstudio archive
    get_url:
      url: "https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.4.1103-amd64.deb"
      dest: /media/penelopeprime/.tools/rstudio-1.4.1103-amd64.deb
      mode: '0777'
    run_once: true

  - name: Install RStudio Deb package
    apt:
      deb: /media/penelopeprime/.tools/rstudio-1.4.1103-amd64.deb

  - name: Copy Rstudio Desktop file
    copy:
      src: /usr/share/applications/rstudio.desktop
      dest: /home/training/Desktop/rstudio.desktop
      remote_src: yes
      owner: training
      group: training
      mode: '0777'

  - name: Add R extra repo
    ansible.builtin.apt_repository:
      repo: ppa:marutter/c2d4u3.5

  - name: Install R cran and dependencies
    apt:
      name:
        - libxml2-dev
        - libxml2
        - liblzma-dev
        - curl
        - libcurl4-openssl-dev
        - build-essential
        - libcurl4-gnutls-dev
        - libssl-dev
        - libgit2-dev
        - pkg-config
        - default-jre
        - default-jdk
        - r-cran-rjava
      update_cache: yes

  - name: Re-configrue R
    shell: sudo R CMD javareconf

  - name: Create R pkg installer file
    file:
      path: /usr/local/pkg_install.R
      state: touch
      mode: '0777'

  - name: Fill in R pkg installer file
    blockinfile:
      path: /usr/local/pkg_install.R
      block: |
        if (!requireNamespace("BiocManager"))
          install.packages("BiocManager")
        BiocManager::install(update = TRUE, ask = FALSE)
        BiocManager::install(c("devtools"), ask = FALSE)
        library(devtools)


  - name: Install R pkgs
    shell: Rscript /usr/local/pkg_install.R
    become: yes
    become_user: training
    args:
      chdir: /home/training/
